name: Docker Image CI

on:
  push:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Install dependencies
      run: dotnet restore ./PontoOpen.Api
    - name: Build
      run: dotnet build ./PontoOpen.Api --configuration Release
    - name: Test
      run: dotnet test ./PontoOpen.Test
    - name: Build-Image-Docker
      run: docker build PontoOpen/PontoOpen.Api/Dockerfile --no-cache -t brunobentocaina/ponto-open-api:stating
    - name: Push
      run: |
        docker login -u brunobentocaina -p ${{ secrets.DOCKER_HUB_KEY }}
        docker push brunobentocaina/ponto-open-api:stating
